=== Abuyunus007/l2-rust/dist/game/data/xsd/playerTemplate.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="1">
				<xs:element name="classId" minOccurs="1" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:nonNegativeInteger">
							<xs:minInclusive value="0" />
							<xs:maxInclusive value="136" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="staticData" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:sequence maxOccurs="1" minOccurs="1">
							<xs:element type="xs:nonNegativeInteger" name="baseINT" minOccurs="1" maxOccurs="1" />
							<xs:element type="xs:nonNegativeInteger" name="baseSTR" minOccurs="1" maxOccurs="1" />
							<xs:element type="xs:nonNegativeInteger" name="baseCON" minOccurs="1" maxOccurs="1" />
							<xs:element type="xs:nonNegativeInteger" name="baseMEN" minOccurs="1" maxOccurs="1" />
							<xs:element type="xs:nonNegativeInteger" name="baseDEX" minOccurs="1" maxOccurs="1" />
							<xs:element type="xs:nonNegativeInteger" name="baseWIT" minOccurs="1" maxOccurs="1" />
							<xs:element name="creationPoints" minOccurs="1" maxOccurs="1">
								<xs:complexType>
									<xs:sequence maxOccurs="1" minOccurs="0">
										<xs:element name="node" maxOccurs="unbounded" minOccurs="1">
											<xs:complexType>
												<xs:attribute type="xs:integer" name="x" use="required" />
												<xs:attribute type="xs:integer" name="y" use="required" />
												<xs:attribute type="xs:integer" name="z" use="required" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element type="xs:positiveInteger" name="basePAtk" minOccurs="1" maxOccurs="1" />
							<xs:element type="xs:positiveInteger" name="baseCritRate" minOccurs="1" maxOccurs="1" />
							<xs:element name="baseAtkType" minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base="xs:token">
										<xs:enumeration value="FIST" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element type="xs:positiveInteger" name="basePAtkSpd" minOccurs="1" maxOccurs="1" />
							<xs:element name="basePDef" minOccurs="1" maxOccurs="1">
								<xs:complexType>
									<xs:sequence maxOccurs="1" minOccurs="1">
										<xs:element type="xs:positiveInteger" name="chest" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:positiveInteger" name="legs" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:positiveInteger" name="head" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:positiveInteger" name="feet" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:positiveInteger" name="gloves" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:positiveInteger" name="underwear" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:positiveInteger" name="cloak" minOccurs="1" maxOccurs="1" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element type="xs:positiveInteger" name="baseMAtk" minOccurs="1" maxOccurs="1" />
							<xs:element name="baseMDef" minOccurs="1" maxOccurs="1">
								<xs:complexType>
									<xs:sequence maxOccurs="1" minOccurs="1">
										<xs:element type="xs:positiveInteger" name="rear" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:positiveInteger" name="lear" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:positiveInteger" name="rfinger" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:positiveInteger" name="lfinger" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:positiveInteger" name="neck" minOccurs="1" maxOccurs="1" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element type="xs:nonNegativeInteger" name="baseCanPenetrate" minOccurs="1" maxOccurs="1" />
							<xs:element type="xs:positiveInteger" name="baseAtkRange" minOccurs="1" maxOccurs="1" />
							<xs:element name="baseDamRange" minOccurs="1" maxOccurs="1">
								<xs:complexType>
									<xs:sequence maxOccurs="1" minOccurs="1">
										<xs:element type="xs:nonNegativeInteger" name="verticalDirection" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:nonNegativeInteger" name="horizontalDirection" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:nonNegativeInteger" name="distance" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:nonNegativeInteger" name="width" minOccurs="1" maxOccurs="1" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element type="xs:positiveInteger" name="baseRndDam" minOccurs="1" maxOccurs="1" />
							<xs:element name="baseMoveSpd" minOccurs="1" maxOccurs="1">
								<xs:complexType>
									<xs:sequence maxOccurs="1" minOccurs="1">
										<xs:element type="xs:positiveInteger" name="walk" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:positiveInteger" name="run" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:positiveInteger" name="slowSwim" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:positiveInteger" name="fastSwim" minOccurs="1" maxOccurs="1" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element type="xs:positiveInteger" name="baseBreath" minOccurs="1" maxOccurs="1" />
							<xs:element type="xs:positiveInteger" name="baseSafeFall" minOccurs="1" maxOccurs="1" />
							<xs:element name="collisionMale" minOccurs="1" maxOccurs="1">
								<xs:complexType>
									<xs:sequence maxOccurs="1" minOccurs="1">
										<xs:element type="xs:decimal" name="radius" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:decimal" name="height" minOccurs="1" maxOccurs="1" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="collisionFemale" minOccurs="1" maxOccurs="1">
								<xs:complexType>
									<xs:sequence maxOccurs="1" minOccurs="1">
										<xs:element type="xs:decimal" name="radius" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:decimal" name="height" minOccurs="1" maxOccurs="1" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="lvlUpgainData" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:sequence maxOccurs="1" minOccurs="1">
							<xs:element name="level" maxOccurs="85" minOccurs="85">
								<xs:complexType>
									<xs:sequence maxOccurs="1" minOccurs="1">
										<xs:element type="xs:decimal" name="hp" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:decimal" name="mp" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:decimal" name="cp" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:decimal" name="hpRegen" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:decimal" name="mpRegen" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:decimal" name="cpRegen" minOccurs="1" maxOccurs="1" />
									</xs:sequence>
									<xs:attribute name="val" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:positiveInteger">
												<xs:minInclusive value="1" />
												<xs:maxInclusive value="85" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Abuyunus007/l2-rust/dist/game/data/stats/players/templates/StartingClass/OrcMystic.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../xsd/playerTemplate.xsd">
	<classId>49</classId>
	<staticData>
		<baseINT>31</baseINT>
		<baseSTR>27</baseSTR>
		<baseCON>31</baseCON>
		<baseMEN>42</baseMEN>
		<baseDEX>24</baseDEX>
		<baseWIT>15</baseWIT>
		<creationPoints>
			<node x="-56733" y="-113459" z="-690" />
			<node x="-56686" y="-113470" z="-690" />
			<node x="-56728" y="-113610" z="-690" />
			<node x="-56693" y="-113610" z="-690" />
			<node x="-56743" y="-113757" z="-690" />
			<node x="-56682" y="-113730" z="-690" />
		</creationPoints>
		<basePAtk>3</basePAtk>
		<baseCritRate>4</baseCritRate>
		<baseAtkType>FIST</baseAtkType>
		<basePAtkSpd>300</basePAtkSpd>
		<basePDef>
			<chest>15</chest>
			<legs>8</legs>
			<head>12</head>
			<feet>7</feet>
			<gloves>8</gloves>
			<underwear>3</underwear>
			<cloak>1</cloak>
		</basePDef>
		<baseMAtk>6</baseMAtk>
		<baseMDef>
			<rear>9</rear>
			<lear>9</lear>
			<rfinger>5</rfinger>
			<lfinger>5</lfinger>
			<neck>13</neck>
		</baseMDef>
		<baseCanPenetrate>0</baseCanPenetrate>
		<baseAtkRange>25</baseAtkRange>
		<baseDamRange>
			<verticalDirection>0</verticalDirection>
			<horizontalDirection>0</horizontalDirection>
			<distance>26</distance>
			<width>120</width>
		</baseDamRange>
		<baseRndDam>10</baseRndDam>
		<baseMoveSpd>
			<walk>70</walk>
			<run>121</run>
			<slowSwim>50</slowSwim>
			<fastSwim>50</fastSwim>
		</baseMoveSpd>
		<baseBreath>90</baseBreath>
		<baseSafeFall>250</baseSafeFall>
		<collisionMale>
			<radius>7.0</radius>
			<height>27.5</height>
		</collisionMale>
		<collisionFemale>
			<radius>8.0</radius>
			<height>25.5</height>
		</collisionFemale>
	</staticData>
	<lvlUpgainData>
		<level val="1">
			<hp>95.0</hp>
			<mp>40.0</mp>
			<cp>47.5</cp>
			<hpRegen>2.0</hpRegen>
			<mpRegen>0.9</mpRegen>
			<cpRegen>2.0</cpRegen>
		</level>
		<level val="2">
			<hp>110.47</hp>
			<mp>47.28</mp>
			<cp>55.235</cp>
			<hpRegen>2.05</hpRegen>
			<mpRegen>0.9</mpRegen>
			<cpRegen>2.0</cpRegen>
		</level>
		<level val="3">
			<hp>126.11</hp>
			<mp>54.64</mp>
			<cp>63.055</cp>
			<hpRegen>2.1</hpRegen>
			<mpRegen>0.9</mpRegen>
			<cpRegen>2.0</cpRegen>
		</level>
		<level val="4">
			<hp>141.92</hp>
			<mp>62.08</mp>
			<cp>70.96</cp>
			<hpRegen>2.15</hpRegen>
			<mpRegen>0.9</mpRegen>
			<cpRegen>2.0</cpRegen>
		</level>
		<level val="5">
			<hp>157.9</hp>
			<mp>69.6</mp>
			<cp>78.95</cp>
			<hpRegen>2.2</hpRegen>
			<mpRegen>0.9</mpRegen>
			<cpRegen>2.0</cpRegen>
		</level>
		<level val="6">
			<hp>174.05</hp>
			<mp>77.2</mp>
			<cp>87.025</cp>
			<hpRegen>2.25</hpRegen>
			<mpRegen>0.9</mpRegen>
			<cpRegen>2.0</cpRegen>
		</level>
		<level val="7">
			<hp>190.37</hp>
			<mp>84.88</mp>
			<cp>95.185</cp>
			<hpRegen>2.3</hpRegen>
			<mpRegen>0.9</mpRegen>
			<cpRegen>2.0</cpRegen>
		</level>
		<level val="8">
			<hp>206.86</hp>
			<mp>92.64</mp>
			<cp>103.43</cp>
			<hpRegen>2.35</hpRegen>
			<mpRegen>0.9</mpRegen>
			<cpRegen>2.0</cpRegen>
		</level>
		<level val="9">
			<hp>223.52</hp>
			<mp>100.48</mp>
			<cp>111.76</cp>
			<hpRegen>2.4</hpRegen>
			<mpRegen>0.9</mpRegen>
			<cpRegen>2.0</cpRegen>
		</level>
		<level val="10">
			<hp>240.35</hp>
			<mp>108.4</mp>
			<cp>120.175</cp>
			<hpRegen>2.45</hpRegen>
			<mpRegen>0.9</mpRegen>
			<cpRegen>2.0</cpRegen>
		</level>
		<level val="11">
			<hp>257.35</hp>
			<mp>116.4</mp>
			<cp>128.675</cp>
			<hpRegen>2.5</hpRegen>
			<mpRegen>1.2</mpRegen>
			<cpRegen>2.5</cpRegen>
		</level>
		<level val="12">
			<hp>274.52</hp>
			<mp>124.48</mp>
			<cp>137.26</cp>
			<hpRegen>2.6</hpRegen>
			<mpRegen>1.2</mpRegen>
			<cpRegen>2.5</cpRegen>
		</level>
		<level val="13">
			<hp>291.86</hp>
			<mp>132.64</mp>
			<cp>145.93</cp>
			<hpRegen>2.7</hpRegen>
			<mpRegen>1.2</mpRegen>
			<cpRegen>2.5</cpRegen>
		</level>
		<level val="14">
			<hp>309.37</hp>
			<mp>140.88</mp>
			<cp>154.685</cp>
			<hpRegen>2.8</hpRegen>
			<mpRegen>1.2</mpRegen>
			<cpRegen>2.5</cpRegen>
		</level>
		<level val="15">
			<hp>327.05</hp>
			<mp>149.2</mp>
			<cp>163.525</cp>
			<hpRegen>2.9</hpRegen>
			<mpRegen>1.2</mpRegen>
			<cpRegen>2.5</cpRegen>
		</level>
		<level val="16">
			<hp>344.9</hp>
			<mp>157.6</mp>
			<cp>172.45</cp>
			<hpRegen>3.0</hpRegen>
			<mpRegen>1.2</mpRegen>
			<cpRegen>2.5</cpRegen>
		</level>
		<level val="17">
			<hp>362.92</hp>
			<mp>166.08</mp>
			<cp>181.46</cp>
			<hpRegen>3.1</hpRegen>
			<mpRegen>1.2</mpRegen>
			<cpRegen>2.5</cpRegen>
		</level>
		<level val="18">
			<hp>381.11</hp>
			<mp>174.64</mp>
			<cp>190.555</cp>
			<hpRegen>3.2</hpRegen>
			<mpRegen>1.2</mpRegen>
			<cpRegen>2.5</cpRegen>
		</level>
		<level val="19">
			<hp>399.47</hp>
			<mp>183.28</mp>
			<cp>199.735</cp>
			<hpRegen>3.3</hpRegen>
			<mpRegen>1.2</mpRegen>
			<cpRegen>2.5</cpRegen>
		</level>
		<level val="20">
			<hp>418.0</hp>
			<mp>192.0</mp>
			<cp>209.0</cp>
			<hpRegen>3.4</hpRegen>
			<mpRegen>1.2</mpRegen>
			<cpRegen>2.5</cpRegen>
		</level>
		<level val="21">
			<hp>436.7</hp>
			<mp>200.8</mp>
			<cp>218.35</cp>
			<hpRegen>3.5</hpRegen>
			<mpRegen>1.5</mpRegen>
			<cpRegen>3.5</cpRegen>
		</level>
		<level val="22">
			<hp>455.57</hp>
			<mp>209.68</mp>
			<cp>227.785</cp>
			<hpRegen>3.6</hpRegen>
			<mpRegen>1.5</mpRegen>
			<cpRegen>3.5</cpRegen>
		</level>
		<level val="23">
			<hp>474.61</hp>
			<mp>218.64</mp>
			<cp>237.305</cp>
			<hpRegen>3.7</hpRegen>
			<mpRegen>1.5</mpRegen>
			<cpRegen>3.5</cpRegen>
		</level>
		<level val="24">
			<hp>493.82</hp>
			<mp>227.68</mp>
			<cp>246.91</cp>
			<hpRegen>3.8</hpRegen>
			<mpRegen>1.5</mpRegen>
			<cpRegen>3.5</cpRegen>
		</level>
		<level val="25">
			<hp>513.2</hp>
			<mp>236.8</mp>
			<cp>256.6</cp>
			<hpRegen>3.9</hpRegen>
			<mpRegen>1.5</mpRegen>
			<cpRegen>3.5</cpRegen>
		</level>
		<level val="26">
			<hp>532.75</hp>
			<mp>246.0</mp>
			<cp>266.375</cp>
			<hpRegen>4.0</hpRegen>
			<mpRegen>1.5</mpRegen>
			<cpRegen>3.5</cpRegen>
		</level>
		<level val="27">
			<hp>552.47</hp>
			<mp>255.28</mp>
			<cp>276.235</cp>
			<hpRegen>4.1</hpRegen>
			<mpRegen>1.5</mpRegen>
			<cpRegen>3.5</cpRegen>
		</level>
		<level val="28">
			<hp>572.36</hp>
			<mp>264.64</mp>
			<cp>286.18</cp>
			<hpRegen>4.2</hpRegen>
			<mpRegen>1.5</mpRegen>
			<cpRegen>3.5</cpRegen>
		</level>
		<level val="29">
			<hp>592.42</hp>
			<mp>274.08</mp>
			<cp>296.21</cp>
			<hpRegen>4.3</hpRegen>
			<mpRegen>1.5</mpRegen>
			<cpRegen>3.5</cpRegen>
		</level>
		<level val="30">
			<hp>612.65</hp>
			<mp>283.6</mp>
			<cp>306.325</cp>
			<hpRegen>4.4</hpRegen>
			<mpRegen>1.5</mpRegen>
			<cpRegen>3.5</cpRegen>
		</level>
		<level val="31">
			<hp>633.05</hp>
			<mp>293.2</mp>
			<cp>316.525</cp>
			<hpRegen>4.5</hpRegen>
			<mpRegen>1.8</mpRegen>
			<cpRegen>4.5</cpRegen>
		</level>
		<level val="32">
			<hp>653.62</hp>
			<mp>302.88</mp>
			<cp>326.81</cp>
			<hpRegen>4.6</hpRegen>
			<mpRegen>1.8</mpRegen>
			<cpRegen>4.5</cpRegen>
		</level>
		<level val="33">
			<hp>674.36</hp>
			<mp>312.64</mp>
			<cp>337.18</cp>
			<hpRegen>4.7</hpRegen>
			<mpRegen>1.8</mpRegen>
			<cpRegen>4.5</cpRegen>
		</level>
		<level val="34">
			<hp>695.27</hp>
			<mp>322.48</mp>
			<cp>347.635</cp>
			<hpRegen>4.8</hpRegen>
			<mpRegen>1.8</mpRegen>
			<cpRegen>4.5</cpRegen>
		</level>
		<level val="35">
			<hp>716.35</hp>
			<mp>332.4</mp>
			<cp>358.175</cp>
			<hpRegen>4.9</hpRegen>
			<mpRegen>1.8</mpRegen>
			<cpRegen>4.5</cpRegen>
		</level>
		<level val="36">
			<hp>737.6</hp>
			<mp>342.4</mp>
			<cp>368.8</cp>
			<hpRegen>5.0</hpRegen>
			<mpRegen>1.8</mpRegen>
			<cpRegen>4.5</cpRegen>
		</level>
		<level val="37">
			<hp>759.02</hp>
			<mp>352.48</mp>
			<cp>379.51</cp>
			<hpRegen>5.1</hpRegen>
			<mpRegen>1.8</mpRegen>
			<cpRegen>4.5</cpRegen>
		</level>
		<level val="38">
			<hp>780.61</hp>
			<mp>362.64</mp>
			<cp>390.305</cp>
			<hpRegen>5.2</hpRegen>
			<mpRegen>1.8</mpRegen>
			<cpRegen>4.5</cpRegen>
		</level>
		<level val="39">
			<hp>802.37</hp>
			<mp>372.88</mp>
			<cp>401.185</cp>
			<hpRegen>5.3</hpRegen>
			<mpRegen>1.8</mpRegen>
			<cpRegen>4.5</cpRegen>
		</level>
		<level val="40">
			<hp>824.3</hp>
			<mp>383.2</mp>
			<cp>412.15</cp>
			<hpRegen>5.4</hpRegen>
			<mpRegen>1.8</mpRegen>
			<cpRegen>4.5</cpRegen>
		</level>
		<level val="41">
			<hp>846.4</hp>
			<mp>393.6</mp>
			<cp>423.2</cp>
			<hpRegen>5.5</hpRegen>
			<mpRegen>2.1</mpRegen>
			<cpRegen>5.5</cpRegen>
		</level>
		<level val="42">
			<hp>868.67</hp>
			<mp>404.08</mp>
			<cp>434.335</cp>
			<hpRegen>5.6</hpRegen>
			<mpRegen>2.1</mpRegen>
			<cpRegen>5.5</cpRegen>
		</level>
		<level val="43">
			<hp>891.11</hp>
			<mp>414.64</mp>
			<cp>445.555</cp>
			<hpRegen>5.7</hpRegen>
			<mpRegen>2.1</mpRegen>
			<cpRegen>5.5</cpRegen>
		</level>
		<level val="44">
			<hp>913.72</hp>
			<mp>425.28</mp>
			<cp>456.86</cp>
			<hpRegen>5.8</hpRegen>
			<mpRegen>2.1</mpRegen>
			<cpRegen>5.5</cpRegen>
		</level>
		<level val="45">
			<hp>936.5</hp>
			<mp>436.0</mp>
			<cp>468.25</cp>
			<hpRegen>5.9</hpRegen>
			<mpRegen>2.1</mpRegen>
			<cpRegen>5.5</cpRegen>
		</level>
		<level val="46">
			<hp>959.45</hp>
			<mp>446.8</mp>
			<cp>479.725</cp>
			<hpRegen>6.0</hpRegen>
			<mpRegen>2.1</mpRegen>
			<cpRegen>5.5</cpRegen>
		</level>
		<level val="47">
			<hp>982.57</hp>
			<mp>457.68</mp>
			<cp>491.285</cp>
			<hpRegen>6.1</hpRegen>
			<mpRegen>2.1</mpRegen>
			<cpRegen>5.5</cpRegen>
		</level>
		<level val="48">
			<hp>1005.86</hp>
